### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by JayHoltslander** [uamv/templates-mainwp-client-reports#1]
> Ensure @records are being retained for more than the necessary number of days. The Code Snippets extension can be used to **[check](https://github.com/uamv/snippets-mainwp-code-snippets/blob/master/child-report-period-get.php)** and **[set](https://github.com/uamv/snippets-mainwp-code-snippets/blob/master/child-report-period-set.php)** this value.

404 links. More info?

**Comment by uamv** [comment]
Thanks for catching that. Should be fixed now.
